require: 
  - rubocop-minitest
  - rubocop-rails
  - rubocop-performance

AllCops:
  Exclude:
    - "db/schema.rb"
    - "bin/**/*"
    - "data/**/*"
    - "log/**/*"
    - "tmp/**/*"
    - "node_modules/**/*"
    - "vendor/**/*"
  TargetRubyVersion: 3.3
  NewCops: enable

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Layout/LineLength:
  AllowedPatterns: ['^# ']
Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Lint/DeprecatedOpenSSLConstant:
  Enabled: true
Lint/MixedRegexpCaptureTypes:
  Enabled: true

Metrics/AbcSize:
  Enabled: true
  Exclude:
    - "db/migrate/**/*"
Metrics/BlockLength:
  Enabled: false
Metrics/BlockNesting:
  Max: 4
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: true
  Exclude:
    - "db/migrate/**/*"
Metrics/PerceivedComplexity:
  Enabled: true
  Exclude:
    - "db/migrate/**/*"

Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false

Rails/ActionOrder:
  ExpectedOrder:
    - index
    - new
    - create
    - show
    - edit
    - update
    - destroy
Rails/DynamicFindBy:
  Enabled: true
  AllowedMethods: [] # We add the methods we define ourselves
Rails/HasAndBelongsToMany:
  Enabled: false

Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true
Style/SlicingWithRange:
  Enabled: true
Style/RedundantFetchBlock:
  Enabled: true
Style/RedundantRegexpCharacterClass:
  Enabled: true
Style/RedundantRegexpEscape:
  Enabled: true