name: Cachix

on:
  push:
    branches:
      - main
      - 'stable/**'

jobs:
  packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v23
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Cachix
        uses: cachix/cachix-action@v13
        with:
          name: feed-reader
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build -L --no-link --impure ".#feed-reader.env"
      - run: nix build -L --no-link --impure ".#feed-reader"
  shell:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v23
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Cachix
        uses: cachix/cachix-action@v13
        with:
          name: feed-reader
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build -L --no-link .#devShells.$(nix eval --impure --expr "builtins.currentSystem").feed-reader
