name: CI

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: "test"
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Cachix
        uses: cachix/cachix-action@v17
        with:
          name: feed-reader
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Install dependencies
        run: nix develop --command npm ci
      - name: Compile assets
        run: nix develop --command nix develop --command rails assets:precompile
      - name: Setup database
        run: |
          nix develop --command pg:start
          nix develop --command rails db:setup
          nix develop --command rails db:migrate
      - name: Run tests
        run: nix develop --command  rails test
      - name: Report coverage
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  lint-ruby:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Cachix
        uses: cachix/cachix-action@v17
        with:
          name: feed-reader
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Lint with rubocop
        run: nix develop --command rubocop -c .rubocop.yml
      - name: Lint with erb_lint
        run: nix develop --command erb_lint --lint-all
      - name: Scan with brakeman
        run: nix develop --command brakeman --no-pager
  lint-node:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Cachix
        uses: cachix/cachix-action@v17
        with:
          name: feed-reader
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Install dependencies
        run: nix develop --command npm ci
      - name: Lint with eslint
        run: nix develop --command npm run lint:js -- --no-fix --max-warnings 0
      - name: Lint with stylelint
        run: nix develop --command npm run lint:css -- --max-warnings 0
  lint-nix:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Lint with nixpkgs-fmt
        run: nix develop --command nixpkgs-fmt --check flake.nix module.nix
  precompile:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: "test"
    steps:
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Cachix
        uses: cachix/cachix-action@v17
        with:
          name: feed-reader
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Install dependencies
        run: nix develop --command npm ci
      - name: Compile assets
        run: nix develop --command nix develop --command rails assets:precompile
